### ISSUE TITLE
regression in the latest versions: "yesqa" started to remove required "Flake8-print" comments (but all was fine before)

### ISSUE THREAD

**Issue by simon-liebehenschel** [asottile/yesqa#121]
# Sample code
```python
print("Hello, World!")  # noqa: T001
```

# Command

```bash
pre-commit run --all-files
```

# Old behavior 
Run result: no errors, no changes.

# Current behavior
```bash
pyupgrade................................................................Passed
pycln....................................................................Passed
check yaml...........................................(no files to check)Skipped
check for added large files..............................................Passed
check json...........................................(no files to check)Skipped
check for broken symlinks............................(no files to check)Skipped
check toml...........................................(no files to check)Skipped
detect destroyed symlinks................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
debug statements (python)................................................Passed
absolufy-imports.........................................................Passed
isort....................................................................Passed
black....................................................................Passed
prettier.................................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

_local.py:1:1: T201 print found.

mypy.....................................................................Passed
Strip unnecessary `# noqa`s..............................................Failed
- hook id: yesqa
- exit code: 1

Rewriting _local.py

check blanket noqa.......................................................Passed
check blanket type ignore................................................Passed
check for not-real mock methods..........................................Passed
codespell................................................................Passed
pydocstyle...............................................................Passed
```

# .pre-commit-config.yaml

```yaml
fail_fast: False

default_language_version:
  # force all unspecified python hooks to run python 3.10
  python: python3.10

repos:
  # Disabling reason:
  #   The "shellcheck" requires Docker, but we do not have it at GitLab by default.
  #   Maybe we can use https://gitlab.com/megabyte-labs/docker/codeclimate/shellcheck#standalone-integration as an alternative.
  #  - repo: https://github.com/koalaman/shellcheck-precommit
  #    rev: v0.8.0
  #    hooks:
  #      - id: shellcheck

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/hadialqattan/pycln
    rev: v1.3.3
    hooks:
      - id: pycln
        args: [--config=pycln.cfg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents, --unsafe] # Use `unsafe` to support GitLab `!reference` tag.
      - id: check-added-large-files
        args: [--maxkb=851] # Increase the limit to allow including all JSON files in the "data/" directory.
      - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements

  # TODO: Raises "ModuleNotFoundError: No module named 'cleo'" exception when used with Poetry.
  #  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  #    rev: v1.2.2
  #    hooks:
  #      - id: python-safety-dependencies-check

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        args: ["--never", "--application-directories=."]
        exclude: "test_.*"

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length=160]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        stages: [commit]

  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          [
            "flake8-2020",
            "flake8-print",
            "flake8-bugbear",
            "flake8-simplify",
            "flake8-comprehensions",
            "flake8-pytest-style",
            "flake8-return",
            "flake8-classmethod-staticmethod",
            "pep8-naming",
          ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.960
    hooks:
      - id: mypy
        args: ["--namespace-packages", "--explicit-package-bases"]
        # Because 'pre-commit' runs 'mypy' from an isolated virtualenv (without your dependencies) you may also find it useful
        # to add the typed dependencies to 'additional_dependencies' so 'mypy' can better perform dynamic analysis
        additional_dependencies: [
            # No need to list everything from 'requirements.txt': only add typed dependencies which break typing when are missing.
            # Running 'mypy' directly and via 'pre-commit' must produce the same result.
            # More details: https://github.com/pre-commit/mirrors-mypy/issues/3#issuecomment-547994284
            "pydantic",
            "pendulum",
            "pytest",
            "numpy",
            "more_itertools",
            "aiohttp[speedups]",
            "fastapi",
            "google-cloud-monitoring",
            "aiohttp-client-cache",
            # Alternative: use https://github.com/asottile/types-all to install all 'types-*' with a single line of code:
            # 'types-all',
            "types-MarkupSafe",
            "types-Werkzeug",
            "types-Jinja2",
            "types-futures",
            "types-click",
            "types-ujson",
            "types-toml",
            "types-six",
            "types-requests",
            "types-PyYAML",
            "types-python-dateutil",
            "types-protobuf",
            "types-pkg-resources",
            "types-orjson",
            "types-Flask",
            "types-chardet",
            "types-aiofiles",
            "types-redis",
          ]

  - repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
      - id: yesqa
        additional_dependencies:
          [
            "flake8-2020",
            "flake8-print",
            "flake8-bugbear",
            "flake8-simplify",
            "flake8-comprehensions",
            "flake8-pytest-style",
            "flake8-return",
            "flake8-classmethod-staticmethod",
            "pep8-naming",
            "pydocstyle",
          ]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args: ["--explain", "--ignore=D1,D200,D203,D205,D212,D213,D400,D406,D407,D411,D413,D415"]
# Runs forever due to its known bugs. Enable later.
#-   repo: https://github.com/Yelp/detect-secrets
#    rev: v1.1.0
#    hooks:
#    -   id: detect-secrets
#        args: ['--baseline', '.secrets.baseline']
#        exclude: package.lock.json
```

# Versions
pre-commit 2.19.0
