### ISSUE TITLE
Add support for the flake8 arguments

### ISSUE THREAD

**Issue by Cjkjvfnby** [asottile/yesqa#144]
In my pre-commit, I run flake8 3 times on different folders with different configs.  

It would be great it would be possible to pass additional arguments to the hook and pass them to the flake. 

```yaml
      - id: yesqa
        name: flake8 for scripting
        args:
          - --extend-exclude=default/python/*,test-scripting/*,cmake/*,doc/*,check/*
          - --config=default/scripting/tox.ini
```

it should be easy to achieve  with 
```python
from argparse import ArgumentParser
import shlex

a = ["--extend-exclude", "default/python/*", "--config", "default/scripting/tox.ini"]
p = ArgumentParser()
args, unknownargs = p.parse_known_args(a)
print(unknownargs)
# ['--extend-exclude', 'default/python/*', '--config', 'default/scripting/tox.ini'])



# Python 3.3+
flake8_args = ' '.join(shlex.quote(arg) for arg in unknownargs)

print(flake8_args)
# --extend-exclude 'default/ python/*' --config default/scripting/tox.ini
```
