### ISSUE TITLE
Docs request: is this a flake8 plugin or a standalone tool?

### ISSUE THREAD

**Issue by jamesbraza** [asottile/yesqa#156]
Can you add to the `README.md` if this is a `flake8` plugin or a standalone tool?

I ask because I would like to add it to my `pre-commit` under `additional_dependencies` of `flake8`:

```yaml
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-docstrings
```

However, if it's not a flake8 plugin, then I won't do that, and will instead add it as its own hook.

**Comment by asottile** [comment]
the readme shows how to use this -- what are you confused about?

**Comment by jamesbraza** [comment]
Thanks for the rapid response!  I am confused if this would be valid `.pre-commit-config.yaml`:

```yaml
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-docstrings
          - yesqa
```

That is my preferred approach to incorporating `yesqa`.
