### ISSUE TITLE
Incorrrectly removes `flake8-django` noqas

### ISSUE THREAD

**Issue by samamorgan** [asottile/yesqa#184]
I've been testing this against my Django project and have hit an issue that I can't seem to solve.

The following example has the noqa comment removed incorrectly.

```python
class TestModel(models.Model):  # noqa: DJ08, DJ10, DJ11
    pass
```

My config looks like this:

```yaml
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
        additional_dependencies:
          - flake8-django
```

Oddly other `flake8-django` ignores aren't touched, just this specific case. I've tried many iterations of additional_dependencies and none seem to work as expected.
