### ISSUE TITLE
overzealous removal of noqa: E402

### ISSUE THREAD

**Issue by mxr** [asottile/yesqa#19]
Given this setup

`$ cat .pre-commit-config.yaml`
```yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8==3.6.0
- repo: https://github.com/asottile/yesqa
  rev: v0.0.8
  hooks:
  - id: yesqa
    additional_dependencies:
    - flake8==3.6.0
```

`$ cat example.py`
```python
import gevent.monkey
gevent.monkey.patch_all()

from datetime import datetime

print(gevent.spawn(lambda: datetime.now()).get())
```

Then `pre-commit run flake8 --files example.py` fails with 

```
Flake8...................................................................Failed
hookid: flake8

example.py:4:1: E402 module level import not at top of file
```

This is expected. However if I change line 2 (not the reported line 4) to be:

```diff
- gevent.monkey.patch_all()
+ gevent.monkey.patch_all()  # noqa: E402
```

Then `flake8` passes, but `yesqa` will rewrite the file and remove the `noqa`, causing `flake8` to fail again.

Should `yesqa` instead keep that `noqa`? Or should I `noqa: E402` line 4 and any other possible imports I add in the future?
