### ISSUE TITLE
Removes E127 and E131 but then Flake8 reports them

### ISSUE THREAD

**Issue by hugovk** [asottile/yesqa#32]
`.pre-commit-config.yaml` does Black, Flake8 and yesqa:

```yml
repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        args: ["--target-version", "py35"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8

  - repo: https://github.com/asottile/yesqa
    rev: v0.0.11
    hooks:
      - id: yesqa
```

With code something like this, which has `fmt: off` and `fmt: on` to prevent Black rewriting and losing the shape of the matrices, and a couple of `noqa: ` lines to keep Flake8 quiet:

```python
from PIL import Image, ImageFilter


class Abc:
    def test_consistency_3x3(self):
        with Image.open("Tests/images/hopper.bmp"):
            with Image.open("Tests/images/hopper_emboss.bmp"):
                kernel = ImageFilter.Kernel(  # noqa: E127
                    (3, 3),
                    # fmt: off
                    (-1, -1,  0,
                     -1,  0,  1,
                      0,  1,  1),
                    # fmt: on
                    0.3,
                )
                assert kernel

    def assert_aux_channel_preserved(self):
        def create_test_image():
            # fmt: off
            nine_grid_deltas = [  # noqa: E131
                (-1, -1), (-1, 0), (-1, 1),
                 (0, -1),  (0, 0),  (0, 1),
                 (1, -1),  (1, 0),  (1, 1),
            ]
            # fmt: on
            assert nine_grid_deltas
```

Running pre-commit removes the `noqa`s:

```console
$ pre-commit run --files 1.py
black....................................................................Passed
flake8...................................................................Passed
Strip unnecessary `# noqa`s..............................................Failed
hookid: yesqa

Rewriting 1.py
```

```diff
8c8
<                 kernel = ImageFilter.Kernel(  # noqa: E127
---
>                 kernel = ImageFilter.Kernel(
22c22
<             nine_grid_deltas = [  # noqa: E131
---
>             nine_grid_deltas = [
```

But Flake8 now complains about them:

```console
$ pre-commit run --files 1.py
black....................................................................Passed
flake8...................................................................Failed
hookid: flake8

1.py:13:23: E127 continuation line over-indented for visual indent
1.py:24:18: E131 continuation line unaligned for hanging indent

Strip unnecessary `# noqa`s..............................................Passed
```

Maybe this is a bit like https://github.com/asottile/yesqa/issues/19 because the `noqa` applies to the whole bracketed section, not only the single line it is on?

I can share a similar E128 and another E131 if you'd like.
