### ISSUE TITLE
strange inconsistency with N802

### ISSUE THREAD

**Issue by Borda** [asottile/yesqa#91]
Hi, have a question about how to resolve the following issue with `yesqa` removing comments which are quite needed...
In particular, there are these three methods from the pytest package which are overwritten so they has to sta with strange casing but Flake8 complains unless they are ignored... and `yesqa` removed these comments
```
/home/runner/work/MONAI/MONAI/tests/runner.py:33:10: N802 function name 'startTest' should be lowercase
/home/runner/work/MONAI/MONAI/tests/runner.py:40:10: N802 function name 'stopTest' should be lowercase
```
pls see open PR: https://github.com/Project-MONAI/MONAI/pull/3027

**Comment by asottile** [comment]
the README is short and [addresses your question](https://github.com/asottile/yesqa#as-a-pre-commit-hook)

**Comment by Borda** [comment]
well, I am trying to add such dependencies but does not have any effent:
```yaml
  - repo: https://github.com/asottile/yesqa
    rev: v1.2.3
    hooks:
      - id: yesqa
        name: Unused noqa
    additional_dependencies:
      - flake8>=3.8.1
      - flake8-bugbear
      - flake8-comprehensions
      - flake8-executable
      - flake8-pyi
```

**Comment by asottile** [comment]
none of those provide `N`

**Comment by Borda** [comment]
> none of those provide `N`

true, it comes from https://pypi.org/project/pep8-naming/ but adding it also does not help

**Comment by asottile** [comment]
the problem is highlighted in bright yellow: https://results.pre-commit.ci/run/github/214485001/1633013413.H2ZW1F1XQgGwKVIOPx2hpA

**Comment by Borda** [comment]
ohh I see, so the crrect is:
```yaml
  - repo: https://github.com/asottile/yesqa
    rev: v1.2.3
    hooks:
      - id: yesqa
        name: Unused noqa
        additional_dependencies:
          - flake8>=3.8.1
          - flake8-comprehensions
          - pep8-naming
```
